# Generated by Django 6.0 on 2025-12-21 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=150)),
                ('vehicle_desc', models.TextField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('seater', models.PositiveIntegerField()),
                ('engine', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('vehicle_pic', models.ImageField(upload_to='vehicles')),
                ('status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.categories')),
            ],
        ),
    ]
